//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EonTimer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color Setting_Action_Color {
            get {
                return ((global::System.Drawing.Color)(this["Setting_Action_Color"]));
            }
            set {
                this["Setting_Action_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Setting_Action_Interval {
            get {
                return ((int)(this["Setting_Action_Interval"]));
            }
            set {
                this["Setting_Action_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Setting_Action_Count {
            get {
                return ((int)(this["Setting_Action_Count"]));
            }
            set {
                this["Setting_Action_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_Action_Sound {
            get {
                return ((int)(this["Setting_Action_Sound"]));
            }
            set {
                this["Setting_Action_Sound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_Action_Mode {
            get {
                return ((int)(this["Setting_Action_Mode"]));
            }
            set {
                this["Setting_Action_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Setting_Form_AskSave {
            get {
                return ((bool)(this["Setting_Form_AskSave"]));
            }
            set {
                this["Setting_Form_AskSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_Form_OnTop {
            get {
                return ((bool)(this["Setting_Form_OnTop"]));
            }
            set {
                this["Setting_Form_OnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_Form_AutoSave {
            get {
                return ((bool)(this["Setting_Form_AutoSave"]));
            }
            set {
                this["Setting_Form_AutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Setting_Form_Opacity {
            get {
                return ((int)(this["Setting_Form_Opacity"]));
            }
            set {
                this["Setting_Form_Opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_Form_Mini {
            get {
                return ((bool)(this["Setting_Form_Mini"]));
            }
            set {
                this["Setting_Form_Mini"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14000")]
        public int Setting_Timer_Minimum {
            get {
                return ((int)(this["Setting_Timer_Minimum"]));
            }
            set {
                this["Setting_Timer_Minimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Setting_Timer_SleepInterval {
            get {
                return ((int)(this["Setting_Timer_SleepInterval"]));
            }
            set {
                this["Setting_Timer_SleepInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Setting_Timer_Console {
            get {
                return ((int)(this["Setting_Timer_Console"]));
            }
            set {
                this["Setting_Timer_Console"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_Timer_PreciseCalibration {
            get {
                return ((bool)(this["Setting_Timer_PreciseCalibration"]));
            }
            set {
                this["Setting_Timer_PreciseCalibration"] = value;
            }
        }
    }
}
