//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EonTimer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class UserData : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserData defaultInstance = ((UserData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserData())));
        
        public static UserData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-95")]
        public int Calibration_5_Basic {
            get {
                return ((int)(this["Calibration_5_Basic"]));
            }
            set {
                this["Calibration_5_Basic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int Calibration_5_Entralink {
            get {
                return ((int)(this["Calibration_5_Entralink"]));
            }
            set {
                this["Calibration_5_Entralink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Calibration_4_Delay {
            get {
                return ((int)(this["Calibration_4_Delay"]));
            }
            set {
                this["Calibration_4_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int Calibration_4_Second {
            get {
                return ((int)(this["Calibration_4_Second"]));
            }
            set {
                this["Calibration_4_Second"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Calibration_3_Lag {
            get {
                return ((int)(this["Calibration_3_Lag"]));
            }
            set {
                this["Calibration_3_Lag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal Calibration_3_Factor {
            get {
                return ((decimal)(this["Calibration_3_Factor"]));
            }
            set {
                this["Calibration_3_Factor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Target_3_Initial {
            get {
                return ((int)(this["Target_3_Initial"]));
            }
            set {
                this["Target_3_Initial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Target_3_Frame {
            get {
                return ((int)(this["Target_3_Frame"]));
            }
            set {
                this["Target_3_Frame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Target_4_Second {
            get {
                return ((int)(this["Target_4_Second"]));
            }
            set {
                this["Target_4_Second"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int Target_4_Delay {
            get {
                return ((int)(this["Target_4_Delay"]));
            }
            set {
                this["Target_4_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Target_5_Second {
            get {
                return ((int)(this["Target_5_Second"]));
            }
            set {
                this["Target_5_Second"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int Target_5_Delay {
            get {
                return ((int)(this["Target_5_Delay"]));
            }
            set {
                this["Target_5_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int Target_5_SecondaryEntralink {
            get {
                return ((int)(this["Target_5_SecondaryEntralink"]));
            }
            set {
                this["Target_5_SecondaryEntralink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mode_5 {
            get {
                return ((int)(this["Mode_5"]));
            }
            set {
                this["Mode_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mode_4 {
            get {
                return ((int)(this["Mode_4"]));
            }
            set {
                this["Mode_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Mode_3 {
            get {
                return ((int)(this["Mode_3"]));
            }
            set {
                this["Mode_3"] = value;
            }
        }
    }
}
